apiVersion: apps/v1
kind: Deployment
metadata:
  name: golangapp-deployment
  labels:
    app: golangapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: golangapp
  template:
    metadata:
      labels:
        app: golangapp
    spec:
      containers:
      - name: golangapp
        image: public.ecr.aws/v3v9i7i2/golang_apps:latest
        ports:
        - containerPort: 10000
---
apiVersion: v1
kind: Service
metadata:
  name: golangapp
spec:
  type: NodePort
  selector:
    app: golangapp 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 10000
      nodePort: 30007   
